api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import CurrencyViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register('currencies', CurrencyViewSet, base_name='currency')

urlpatterns = [
    path('', include(router.urls)),
]

app/urls.py
app_name = 'app'
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework.documentation import include_docs_urls

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Challenge Bravo",
      default_version='v1',
      description="Test description",
      terms_of_service="",
      contact=openapi.Contact(email=""),
      license=openapi.License(name=""),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('api/v1/', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),

    url(r'', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

backend/core/urls.py
from django.urls import path

from .views import converter, new

app_name = 'site'

urlpatterns = [
    path('', converter, name='index'),
    path('new', new, name='new')
]

core/urls.py
app_name = 'app'
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.conf.urls import url
router = DefaultRouter()
from convert.api.ConvertViewSet import ConvertViewSet
from coin.api.CoinViewSet import CointViewSet



urlpatterns = [
    path('', include(router.urls)),
    url(r'^convert/', ConvertViewSet.as_view({"get": "convert"})),

    url(r'^coin/list/', CointViewSet.as_view({"get": "list"})),
    url(r'^coin/create/', CointViewSet.as_view({"post": "create"})),
    url(r'^coin/update/(?P<pk>[0-9]+|)/$', CointViewSet.as_view({"put": "update"})),
    url(r'^coin/update_all_coin/', CointViewSet.as_view({"put": "update_all_coin"})),
    url(r'^coin/delete/(?P<pk>\w+|)/$', CointViewSet.as_view({"delete": "delete"})),
]

hurb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hurb.base.urls')),
    path('v1/', include('hurb.currency.urls')),
]

backend/core/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _


class MyCoin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_('Updated at')
    )
    codecoin = models.CharField(verbose_name=_('Code Coin'), max_length=4)
    namecoin = models.CharField(verbose_name=_('Name Coin'), max_length=50)
    price = models.FloatField(verbose_name=_('Price USD Coin'), default=0)

    class Meta:
        verbose_name = _('My Coin')
        verbose_name_plural = _('My Coins')
        ordering = ('namecoin',)
        constraints = [
            models.UniqueConstraint(
                fields=['codecoin'],
                name='unique_mycoin_codecoin'
            )
        ]

    def __str__(self) -> str:
        return self.codecoin

backend/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms.widgets import TextInput

from backend.services import ApiCoin, Convert
from .models import MyCoin


def get_coins():
    apicoin = ApiCoin()
    currencies = apicoin.get_currencies()
    if not isinstance(currencies, int):
        currencies = [(k, v['currencyName']) for k, v in currencies.items()]
    else:
        currencies = []

    mycoin = MyCoin.objects.all()
    for coin in mycoin:
        currencies.append((coin.codecoin, coin.namecoin))

    currencies = tuple(currencies)
    return sorted(currencies, key=lambda col: col[1])


def get_value_converter(from_coin, to_coin, amount):
    convert = Convert(from_coin=from_coin, to_coin=to_coin, amount=amount)
    # Returns the already converted value
    value_convert = convert.set_convert()
    return value_convert


class ConverterForm(forms.Form):

    from_coin = forms.ChoiceField(
        label=_('From Currency'),
        widget=forms.Select(
            attrs={
                'class': 'form-select'
            }
        )
    )
    to_coin = forms.ChoiceField(
        label=_('To Currency'),
        widget=forms.Select(
            attrs={
                'class': 'form-select'
            }
        )
    )
    amount = forms.FloatField(
        label=_('Value'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    value_converter = forms.FloatField(
        label=_('Converted Value'),
        required=False,
        widget=forms.TextInput(
            attrs={
                'readonly': 'readonly',
                'class': 'form-control'
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super(ConverterForm, self).__init__(*args, **kwargs)

        self.fields['from_coin'].choices = get_coins()
        self.fields['to_coin'].choices = self.fields['from_coin'].choices

        if self.is_bound:
            self.data = self.data.copy()
            from_coin = self.data['from_coin']
            to_coin = self.data['to_coin']
            amount = float(
                self.data['amount'] if self.data['amount'] != '' else '0'
            )

            if amount > 0:
                self.data['value_converter'] = get_value_converter(
                    from_coin, to_coin, amount
                )

    def clean(self):
        self.cleaned_data = super().clean()

        if not self.cleaned_data.get('amount') or \
                self.cleaned_data.get('amount') <= 0:
            raise ValidationError(_('Please enter a valid value.'))


class MyCoinModelForm(forms.ModelForm):
    price = forms.FloatField(
        label=_('Value in USD'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = MyCoin
        fields = ('codecoin', 'namecoin', 'price')
        widgets = {
            'codecoin': TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'namecoin': TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 1:
            raise ValidationError(_('Please enter a valid value.'))

        return price

backend/core/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.shortcuts import resolve_url as r

from .forms import ConverterForm, MyCoinModelForm


def converter(request):
    if request.method == 'POST':
        form = ConverterForm(request.POST)
        if not form.is_valid():
            return render(request, 'index.html', {'form': form})

        return render(request, 'index.html', {'form': form})
    else:
        return render(request, 'index.html', {'form': ConverterForm()})


def new(request):
    if request.method == 'POST':
        form = MyCoinModelForm(request.POST)
        if not form.is_valid():
            return render(request, 'new.html', {'form': form})

        form.save()
        return HttpResponseRedirect(r('site:index'))
    else:
        return render(request, 'new.html', {'form': MyCoinModelForm()})

backend/core/templates/index.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Conversor de Moedas - Bravo Challenge - Hurb</title>
        <meta name="theme-color" content="#000000">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    </head>

    <body>
        <div class="container">
            <h1 class="text-center display-4 my-3">Conversor de Moedas - Bravo Challenge</h1>

            <div class="row">
                <div class="form-group">
                    <h5 class="text-center">Informe o valor a ser convertido</h5>
                </div>
                <form action="." novalidate method="post" class="col-sm-6  offset-sm-3">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="form-group">
                        <div class="form-floating">
                            {{ form.from_coin.errors }}
                            {{ form.from_coin }}
                            <label for="{{ form.from_coin.id_for_label }}">{{ form.from_coin.label }}</label>
                        </div>
                        <div class="form-floating">
                            {{ form.to_coin.errors }}
                            {{ form.to_coin }}
                            <label for="{{ form.to_coin.id_for_label }}">{{ form.to_coin.label }}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.amount }}
                            <label for="{{ form.amount.id_for_label }}">{{ form.amount.label }}</label>
                            {{ form.amount.errors }}
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.value_converter.errors }}
                            {{ form.value_converter }}
                            <label for="{{ form.value_converter.id_for_label }}">{{ form.value_converter.label }}</label>
                        </div>
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-outline-secondary">Converter</button>
                            <a class="btn btn-success" href="{% url 'site:new' %}" role="button">Cadastrar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>

backend/core/templates/new.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Conversor de Moedas - Bravo Challenge - Hurb</title>
        <meta name="theme-color" content="#000000">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    </head>

    <body>
        <div class="container">
            <h1 class="text-center display-4 my-3">Conversor de Moedas - Bravo Challenge</h1>

            <div class="row">
                <div class="form-group">
                    <h5 class="text-center">Cadastro Nova Moeda</h5>
                </div>
                <form action="/new" novalidate method="post" class="col-sm-6  offset-sm-3">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="form-group">
                        <div class="form-floating">
                            {{ form.codecoin }}
                            <label for="{{ form.codecoin.id_for_label }}">{{ form.codecoin.label }}</label>
                            {{ form.codecoin.errors }}
                        </div>
                        <div class="form-floating">
                            {{ form.namecoin }}
                            <label for="{{ form.namecoin.id_for_label }}">{{ form.namecoin.label }}</label>
                            {{ form.namecoin.errors }}
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.price }}
                            <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
                            {{ form.price.errors }}
                        </div>
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-outline-secondary">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>